config/routes.rb
Blogger::Application.routes.draw do

  resources :articles do
    resources :comments
  end

  resources :tags, only: [:show, :index]

  match 'about',   to: 'static_pages#about'
  match 'diffs', to: 'projects#diffs'
  match 'memory', to: 'projects#memory'

  root to: 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :body, :tag_list, :image, :description

  default_scope order('created_at DESC')

  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image, :styles => { :medium => "120x120>" }


  def tag_list
    list = []
    tags.each {|tag| list << tag.name }
    list.join(', ')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by_name(name) }
    self.tags = new_or_found_tags
  end

end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  # attr_accessible :title, :body

  validates_confirmation_of :password, message: "should match confirmation", if: :password

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  attr_accessible :author_name, :body
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  has_many :taggings
  has_many :articles, through: :taggings

  def articles_with
    Article.all.select do |article| 
      article.tags.map{ |tag| tag.name }.include?(name)
    end

  end

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
  @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(params[:article])

    flash.notice = "article \"#{@article.title}\" successfully created"
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash.notice = "article \"#{@article.title}\" deleted"
    redirect_to articles_path
  end 

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update_attributes(params[:article])
    flash.notice = "article \"#{@article.title}\" successfully updated."
    redirect_to article_path(@article)
  end

end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController

  def new
  end

  def create
    if login(params[:username], params[:password])
      redirect_back_or_to(articles_path, message: "Logged in.")
    else
      flash.now.alert = 'Login failed.'
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, message: 'Logged out!')
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_filter :zero_authors_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]

  def zero_authors_or_authenticated
  unless Author.count == 0 || current_user
    redirect_to root_path
    return false
  end
  end




  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authors }
    end
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/new
  # GET /authors/new.json
  def new
    @author = Author.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @author }
    end
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(params[:author])

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render json: @author, status: :created, location: @author }
      else
        format.html { render action: "new" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /authors/1
  # PUT /authors/1.json
  def update
    @author = Author.find(params[:id])

    respond_to do |format|
      if @author.update_attributes(params[:author])
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @article = Article.find(params[:id])
    @comment = @article.comments.new
  end

  def create
    @comment = Comment.new(params[:comment])
    @comment.article_id = params[:article_id]
    @comment.save

   
    redirect_to article_path(@comment.article)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def diffs
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find(params[:id])
    @articles = @tag.articles_with
  end

  def index
    @tags = Tag.all
  end

end

app/helpers/application_helper.rb
require 'redcarpet_helper.rb'

module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/redcarpet_helper.rb
module RedcarpetHelper
  def markdown(content)
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, space_after_headers: true, fenced_code_blocks: true)
    @markdown.render(content)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>comment by <%= comment.author_name %></h4>
  <p class="comments"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>

</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>

  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>


  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br/>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  

  <p>
    <%= f.label :tag_list %></br>
    <%= f.text_field :tag_list %>
  </p>



  <p>
    <% if @article.image.exists? %>
      <%= image_tag @article.image.url %><br/>
    <% end %>
    <%= f.label :image, 'Attach a new image' %></br>
    <%= f.file_field :image %>
  </p>



  <p>
    <%= f.submit %>
  </p>



<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<body class='intro'>
<ul id="articles">
<% @articles.each do |article| %>
  <li><%= link_to article.title, article_path(article), class: 'article-title' %>
  
  <% if article.description != '' %>
    <div class="description"><%= article.description %></div>
  <% end %>


<div class='text'>
  <% if article.image.exists? %>
    <p class="image"><%= image_tag article.image.url(:original) %></p>
  <% end %>

  <% if article.body.length > 700 %>
    <%= markdown(truncate(article.body, length: 500, separator: ' ')).html_safe %>
    <%= link_to "keep reading", article_path(article), class: 'link' %>
  <% else %>
    <%= markdown(article.body).html_safe %>
  <% end %> 
</div>

</li>

  <% if article != Article.last %>
    <br><br>
  <% end %>
<% end %>


</ul>

<% if current_user %>
  <%= link_to "create a new article", new_article_path, class: 'link' %>
<% end %>
</body>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<body class="info">

<div class='article-title'><%= @article.title %></div>
<div class='description'><%= @article.description %></div>
<br>

<% if @article.image.exists? %>
  <p><%= image_tag @article.image.url(:original) %></p>
<% end %>

<section class='text'>
  <%= markdown(@article.body).html_safe %>
</section>

<% if @article.tags.size > 0 %>
  <p>
    Tags: 
    <% @article.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag) %>
      <%= ' ' %>
    <% end %>  
  </p>
<% end %>

<h3>Comments (<%= @article.comments.count %>)</h3>

  <%= render partial: 'comment', collection: @article.comments %>


<%= render partial: 'comments/form' %>




<% if current_user %>
<%= link_to 'delete article', article_path(@article), method: :delete, confirm: "really delete the article" %> |

<%= link_to 'edit article', edit_article_path(@article) %> 
<% end %>

</body>

app/views/author_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :username %>
    <%= text_field_tag :username %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authors.each do |author| %>
  <tr>
    <td><%= author.username %></td>
    <td><%= author.email %></td>
    <td><%= link_to 'Show', author %></td>
    <td><%= link_to 'Edit', edit_author_path(author) %></td>
    <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<% if current_user %>
  <%= link_to 'New Author', new_author_path %>
<% end %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @author.username %>
</p>

<p>
  <b>Email:</b>
  <%= @author.email %>
</p>

<p>
  <b>Password:</b>
  <%= @author.password %>
</p>

<p>
  <b>Password confirmation:</b>
  <%= @author.password_confirmation %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<h3>Post a comment</h3>

<%= form_for([@article, @comment]) do |f| %>

  <p>
    <%= f.label :author_name, 'Your name:' %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "your comments..." %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>



<% end %>

app/views/projects/diffs.html.erb
<div class="projects">

<div class="article-title">Word Based Diffs</div>
<div class="description">via longest common subsequences</div><br>


<div id="result">
  

</div>

<div id="texts">
  <textarea id="original" placeholder="first version of text..." autofocus="true"></textarea><br>
  <textarea id="revised" placeholder="revised version..."></textarea>    
<div>
<input type="submit" id="btn" value="compare">

  <a class='code-link' href='https://github.com/bebebebebe/diffs'>code on<br>GitHub</a>

<br/>

</div>

app/views/projects/memory.html.erb
<div class="projects">

<div class="article-title">Memory Game</div>
<div class="description"></div><br>

<div id='options'>
  
  <form>
    number of card types:<br>
    <input id='pickNumber' type='number' min='2' max='81' value ='8' name='card types'></input> 
    <input id='memory-btn' class='project-btn' type='button' value='play'></input>
  </form>

</div>


<div id='board'></div>


<div id='message'></div>

<div id='reset'>shuffle<br>cards &<br>restart</div>

  <a class='code-link' href='https://github.com/bebebebebe/memory'>code on<br>GitHub</a>

<br/>

</div>

app/views/static_pages/about.html.erb
<body class="intro">
<div class='article-title'>About</div>

<section class='text'>

<!-- <p>I'm building this site with Ruby on Rails to learn how to make things on the web; I'm using it to write about and demo some programming projects.</p> -->

</section>

<body>

app/views/static_pages/home.html.erb
  <head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <title>D3 Hello World</title>
    <script type="text/javascript" src="http://mbostock.github.com/d3/d3.js?2.4.5"></script>
  </head>

  <body>

    <h1>Welcome</h1>
    


    <%= link_to 'See Articles', articles_path %>

  
  </body>

app/views/tags/index.html.erb
<h1>Tags<h1>


<ul>
<% @tags.each do |tag| %>
  <li><%= link_to tag.name, tag_path(tag) %></li>
<% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles tagged with  <%= @tag.name %></h1>

<ul id="articles">
<% @articles.each do |article| %>
  <li><%= link_to article.title, article_path(article), class: 'article_title' %></li>
<% end %>
</ul>